+fixes
memmed8ov/javascript-learning pull request #1
Opened 2022-12-03 23:27 UTC by memmed8ov

2022-12-03 23:31 UTC, tislib requested changes

2022-12-03 23:31 UTC, tislib commented on 2/react-app/src/App.jsx
> + import {Countries} from './rout/country/country-page';
no space is needed before import command

2022-12-03 23:31 UTC, tislib commented on 2/react-app/src/rout/city/CityAdd.jsx
> +
remove this line

2022-12-05 13:59 UTC, memmed8ov commented
uyuuuu hocaaaaaa

On Sun, Dec 4, 2022, 03:32 Taleh Ibrahimli ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In 2/react-app/src/App.jsx
> <https://github.com/memmed8ov/javascript-learning/pull/1#discussion_r1038884528>
> :
>
> > -        <h1>
> -          hello{props.name}
> -        </h1>
> -      </div>
> -
> -      {props.Children}
> -    </div>
> -  )
> +import { BrowserRouter as Router, Routes, Route, useNavigate } from 'react-router-dom'
> +
> +import AppBar from ***@***.***/material/AppBar';
> +import Box from ***@***.***/material/Box';
> +import Toolbar from ***@***.***/material/Toolbar';
> +import Button from ***@***.***/material/Button';
> +
> + import {Countries} from './rout/country/country-page';
>
> no space is needed before import command
> ------------------------------
>
> In 2/react-app/src/rout/city/CityAdd.jsx
> <https://github.com/memmed8ov/javascript-learning/pull/1#discussion_r1038884556>
> :
>
> > +
> +    return <>
> +        <div>
> +            <br />
> +            <input placeholder='name' style={{ marginLeft: '50px' }} type="text" value={name} onChange={e => setName((e.target.value))} />
> +            <br />
> +            <br />
> +            <input placeholder='code' style={{ marginLeft: '50px' }} type="text" value={code} onChange={e => setCode((e.target.value))} />
> +            <br />
> +            <br />
> +            <button onClick={() => {
> +                let object = {
> +                    "properties": {
> +                        "description": code,
> +                        "name": name
> +
>
> remove this line
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/memmed8ov/javascript-learning/pull/1#pullrequestreview-1203583579>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4ISW7RWKKD5KBW6QV2ABETWLPJ7FANCNFSM6AAAAAASS7ZSPI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-07 10:43 UTC, tislib requested changes

2022-12-07 10:43 UTC, tislib commented on 2/react-app/src/rout/city/CityAdd.jsx
> +
[OPTIONAL] There are useless new lines (multiple new lines is not good practice for code formatting)

2022-12-07 10:43 UTC, tislib commented on 2/react-app/src/rout/city/CityAdd.jsx
> +                        "description": code,
"description": code

why you have named field for description as code.
Please use correct name on field code (it should be description)

2022-12-07 10:43 UTC, tislib commented on 2/react-app/src/rout/city/CityList.jsx
> +    function allcode() {
function name is incorrect, 
Function name should be related to what it is doing.

allcode => loadCountryList OR load

2022-12-07 10:43 UTC, tislib commented on 2/react-app/src/rout/city/CityList.jsx
> +    function allcode() {
[Important]

2022-12-07 10:43 UTC, tislib commented on 2/react-app/src/rout/city/CityUpdate.jsx
> +    const [codeupdate, setCodeUpdate] = useState('')
Same here, code <=> description, the variable name is not related to what it does. please rename it to description

2022-12-07 13:02 UTC, memmed8ov commented on 2/react-app/src/rout/city/CityAdd.jsx
> +                        "description": code,
because country codes were requested.i called the code.
I named it "description" in our previous study

2022-12-07 21:35 UTC, tislib approved these changes

2022-12-07 21:35 UTC, merged